language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install perl libx11-dev libjpeg-dev libpng-dev libtiff5-dev librsvg2-dev libpoppler-glib-dev libgtk2.0-dev libxine2-dev
  
script:
  - wget https://sourceforge.net/projects/eaglemode/files/latest/download --trust-server-names
  - tar xf eaglemode*.tar.bz2
  - cd eaglemode-*/
  - perl make.pl build
  - mkdir -p appdir/usr/lib/eaglemode
  - perl make.pl install dir=$(readlink -f appdir/usr/lib/eaglemode)
  - cd appdir/usr/lib/eaglemode
  - mkdir -p ../../share/doc/eaglemode
  - mv -T doc ../../share/doc/eaglemode
  - ln -s ../../share/doc/eaglemode doc
  - mkdir -p ../../share/eaglemode
  - mv -T res ../../share/eaglemode
  - ln -s ../../share/eaglemode res
  - cd -
  - mkdir -p appdir/usr/bin
  - cd appdir/usr/bin
  - ln -s ../lib/eaglemode/eaglemode eaglemode
  - cd -
  - mkdir -p appdir/usr/lib
  - cd appdir/usr/lib
  - ln -s eaglemode/lib/*.so .
  - cd -
  - mkdir -p appdir/usr/include
  - cd appdir/usr/include
  - ln -s ../lib/eaglemode/include/* .
  - cd -
  - mkdir -p appdir/usr/share/applications/
  - cp ../eaglemode.desktop appdir/usr/share/applications/
  - mkdir -p appdir/usr/share/icons/hicolor/scalable/apps/
  - touch appdir/usr/share/icons/hicolor/scalable/apps/eaglemode.svg # FIXME
  - cp ../eaglemode.desktop appdir/usr/share/applications/
  - find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file Eagle*.AppImage https://transfer.sh/Eagle_Mode-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Eagle*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
